openapi: 3.0.0
info:
  title: Example for a simple tagged union
  description: Example for a simple tagged union
  version: 1.0.0

paths: {} # not technically necessary, but it pleases intellij

components:
  schemas:
    StringAlias:
      type: string
    TransitiveStringAlias:
      $ref: '#/components/schemas/StringAlias'
    ArrayOnAlias:
      type: array
      items:
        $ref: '#/components/schemas/StringAlias'
    SimpleObject:
      type: object
      properties:
        prop:
          type: string
    SimpleEnum:
      type: string
      enum:
        - A
        - B
        - C
    ConstantString:
      type: string
      enum:
        - CONSTANT_VALUE
