openapi: 3.0.0
info:
  title: Example for a simple untagged union
  description: Example for a simple untagged union
  version: 1.0.0

paths: {} # not technically necessary, but it pleases intellij

components:
  schemas:
    A:
      type: array
      items:
        type: string
    B:
      type: object
      properties:
        prop:
          type: string
    Union:
      oneOf:
        - $ref: '#/components/schemas/A'
        - $ref: '#/components/schemas/B'
        - type: string
